#!/usr/bin/env bash

if ! command -v sqlite3 &> /dev/null
then
    echo "sqlite3 could not be found, please install it first."
    exit
fi

DB_FILE="db/vimcolorschemes.db"

if [ -f "$DB_FILE" ]; then
    rm "$DB_FILE"
    echo "Database '$DB_FILE' has been deleted."
else
    echo "Database '$DB_FILE' does not exist."
fi

db/setup
